version: 1.0.{build}
image: Visual Studio 2013
build_script:
- cmd: >-
    hg clone https://jeromnimo@bitbucket.org/jeromnimo/wmv_sdk
    
    cd wmv_sdk

    .\wmv_set_env.bat

    set WMV_BASE_PATH=C:\projects\wowmodelviewer

    mkdir C:\projects\wowmodelviewer\build

    cd C:\projects\wowmodelviewer\build

    cmake -G "Visual Studio 12 2013" ..\src

    cmake --build . --target release --config Release
test: off
